# This file is part of the diimpp/payever-gallery package.
# (c) Dmitri Perunov

payever_api_gallery_index:
    path: /
    methods: [GET]
    defaults:
        _controller: payever.controller.gallery:indexAction
