# This file is part of the diimpp/payever-gallery package.
# (c) Dmitri Perunov

payever_api_gallery:
    resource: @PayeverApiBundle/Resources/config/routing/gallery.yml
    prefix: /galleries

payever_api_image:
    resource: @PayeverApiBundle/Resources/config/routing/image.yml
    prefix: /images
